sudo: required
dist: trusty
language: c
cache:
  apt: true
  directories:
    - $HOME/.opam
install:
- sudo add-apt-repository --yes ppa:avsm/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq -y opam
- opam init -y
- eval $(opam config env)
- opam config var root
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
- opam install -y ocamlfind ocamlgraph
- git clone --depth=1 https://github.com/coq/coq
- if [ $(opam show --field=source-hash coq) = $(set -e 's/\(.\{8\}\).(/\1/' coq/.git/refs/heads/master) ] ; then true ; else opam uninstall coq ; fi ; rm -rf coq
- travis_wait opam install -y coq.dev
- opam list
script:
- autoconf
- ./configure
- make || exit $?
- make test-suite
